### ISSUE TITLE
SDK Requests Failing After Upgrading Campaign Instance to 8.6.3 - Internal Server Error

### ISSUE THREAD

**Issue by 4reha** [adobe/acc-js-sdk#112]
After upgrading my Adobe Campaign instance from version 8.6.2 to 8.6.3, all requests made using the `@adobe/acc-js-sdk` are failing with a `CampaignException`. The error specifically occurs when calling the `xtk:persist#GetEntityIfMoreRecent` method.

#### Expected Behavior:

The requests should execute successfully without any errors, as they did in version `8.6.2`.

#### Actual Behavior:

Every request fails with the following exception:

```js
CampaignException {
  name: 'CampaignException',
  message: "500 - Error calling method 'xtk:persist#GetEntityIfMoreRecent': Internal Server Error. <?xml version='1.0'?><SOAP-ENV:Envelope xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Error</faultcode><faultstring xsi:type='xsd:string'>SOP-330023 An error occurred during the SOAP call. You don't have the required rights to view the detail.</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>",
  statusCode: 500,
  methodCall: {
    type: 'SOAP',
    url: 'https://<myInstance>.campaign.adobe.com/nl/jsp/soaprouter.jsp?soapAction=xtk%3Apersist%23GetEntityIfMoreRecent',
    urn: 'xtk:persist',
    methodName: 'GetEntityIfMoreRecent',
    request: {
      url: 'https://<myInstance>.campaign.adobe.com/nl/jsp/soaprouter.jsp?soapAction=xtk%3Apersist%23GetEntityIfMoreRecent',
      method: 'POST',
      headers: [Object],
      data: '<SOAP-ENV:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://xml.apache.org/xml-soap"><SOAP-ENV:Header><X-Security-Token/></SOAP-ENV:Header><SOAP-ENV:Body><m:GetEntityIfMoreRecent xmlns:m="urn:xtk:persist" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><sessiontoken xsi:type="xsd:string"/><pk xsi:type="xsd:string">xtk:schema|xtk:queryDef</pk><md5 xsi:type="xsd:string"/><mustExist xsi:type="xsd:boolean">false</mustExist></m:GetEntityIfMoreRecent></SOAP-ENV:Body></SOAP-ENV:Envelope>'
    },
    response: undefined
  },
  errorCode: '',
  faultCode: '',
  faultString: 'Internal Server Error',
  detail: "<?xml version='1.0'?><SOAP-ENV:Envelope xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Error</faultcode><faultstring xsi:type='xsd:string'>SOP-330023 An error occurred during the SOAP call. You don't have the required rights to view the detail.</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>",
  cause: HttpError {
    statusCode: 500,
    statusText: 'Internal Server Error',
    data: "<?xml version='1.0'?><SOAP-ENV:Envelope xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Error</faultcode><faultstring xsi:type='xsd:string'>SOP-330023 An error occurred during the SOAP call. You don't have the required rights to view the detail.</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>"
  }
}
```

#### Steps to Reproduce:

1. Upgrade an Adobe Campaign instance to version 8.6.3.
2. Make any request using the `@adobe/acc-js-sdk` that involves the xtk:persist#GetEntityIfMoreRecent method.
3. Observe the error in the response.

#### Environment:

- Adobe Campaign Classic Version: 8.6.3
- "@adobe/acc-js-sdk": "^1.1.47"
- Node.js : v20.17.0
![Image](https://github.com/user-attachments/assets/78c8d2e1-298b-4823-ada6-579d7fa19d82)

#### Additional Context: The issue began immediately after upgrading to 8.6.3. All requests that were working before the upgrade are now failing with the above exception.

**Comment by mkiki** [comment]
Hi @4reha , thanks for the detailed report. I'm not aware of any changes between 8.6.2 and 8.6.3 that explain the issue. Is it possible to share the URL of your instance so that I can investigate?

**Comment by 4reha** [comment]
Hi @mkiki, here's my campaign instance URL: `https://sprich-mkt-stage2.campaign.adobe.com`

**Comment by 4reha** [comment]
We were able to find the root cause of the issue.
The IP whitelisting was not activated previously on 8.6.2. It has been activated on 8.6.3 causing the API calls issues.

Thanks

**Comment by mkiki** [comment]
Thanks for letting me know. You should not get a HTTP 500 error though. We have an issue with http error code for authentication (https://github.com/adobe/acc-js-sdk/issues/108) for which I haven't found a good solution just yet.
