### ISSUE TITLE
Wrong charset while updating html source

### ISSUE THREAD

**Issue by francescor93** [adobe/acc-js-sdk#26]
I've encountered this problem in a project where I use this library to update the html source of deliveries in a campaign. After creating the html files externally, we run our tool to load the contents of the files into the related deliveries, with the following code:

```typescript
const d = {
  xtkschema: "nms:delivery",
  _operation: "update",
  _key: "@id",
  id: delivery.id,
  content: {
    html: {
      $source: content
    }
  }
};
await NLWS.xtkSession.write(d);
```

### Expected Behaviour

I expect the content of my html file to be correctly uploaded and visible inside the Adobe Campaign delivery.

### Actual Behaviour

If the html contains some special elements, such as the Italian accented characters (à è ì ò ù), they break after the upload:

What I wrote in my editor (VS Code):  
![image](https://user-images.githubusercontent.com/35368854/157510977-edddec04-f16d-485a-a60a-226b49372040.png)

What I see in Adobe Campaign after running the update query:  
![image](https://user-images.githubusercontent.com/35368854/157511015-98b2b553-312b-4a31-abb6-ae9da7a0534a.png)

### Platform and Version

SDK 1.1.0

### Further information

After investigating, I discovered that there's probably a problem in the request encoding: in the _Content-type_ header, the charset is missing.  
After inserting the UTF-8 charset like this:
![image](https://user-images.githubusercontent.com/35368854/157513124-a9cb466e-6051-4e33-9fba-2264fb25292c.png)
in the _soap.js_ file, the upload was successful:
![image](https://user-images.githubusercontent.com/35368854/157513341-c9db1f0f-ff5d-49ef-85a4-17d7d8beb2ed.png)

So I'm kindly asking if you can update the file with the correct UTF-8 character encoding or at least make it configurable while creating the client, so that issues like mine can be solved.

Thanks in advance.

**Comment by mkiki** [comment]
Hi Francesco, thanks for the detailed report. This is indeed an important issue. Campaign will assume iso-8859-1 if no charset is specified. Version 1.1.1 which will default to UTF-8 charset encoding and allow to override the charset, just in case.

**Comment by francescor93** [comment]
Hi @mkiki, thanks for your quick reply and your fast intervention.
We tested the updated version today and I can confirm that the problem no longer occurs.

**Comment by mkiki** [comment]
Hi @francescor93, glad I could help and thanks for the confirmation. Feel free to send me feedback and suggestions about the SDK.
