### ISSUE TITLE
Add missing hasPackage function

### ISSUE THREAD

**Issue by mkiki** [adobe/acc-js-sdk#5]
After logging in a Campaign instance, the "logon" call returns a list of active packages on the instance. 
Make this list available to the clients and add hasPackage function with 2 syntaxes:

- hasPackage(packageId)
- hasPackage(namespace, name)

**Comment by catholicon** [comment]
Is this different from [hasPackage](https://github.com/adobe/acc-js-sdk#test-if-a-package-exists)?

**Comment by mkiki** [comment]
I had initially added hasPackage to the Client object has described in this request.
In version 1.0; I added support for the application object which happens to also have a hasPackage function (https://docs.adobe.com/content/help/en/campaign-classic/technicalresources/api/m-Application-hasPackage.html) 
Both should return the same thing
